### ISSUE TITLE
2.0.0 release ETA

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/Isango#52]
@effone - I cannot reach you on Discord, so I will ask here - can we focus on 1.2.0 release and finish this plugin soon?

I am here to help you, let me know and I am free for testing :)

Focus:

- [x] Connection Delete Confirmation #69
- [x] Check for inactive gates as per available services and indicate in listing
- [x] Isango Buttons: Structural Improvement #22, #47, #51
- [x] Possible problem with other required fields #43
- [x] Registration IP not captured #41
- [x] Send a PM to newly registered users #7
- [x] Disable registration using Isango (only login) #44, #45
- [x] SCSS and MAP files for CSS compilation #37
- [x] Bump plugin version in the next release #36
- [x] Settings display order irregularity #58 
- [x] Purge connections while deleting user #60 
- [x] Allow Single Connection Per Service #70
- [x] Random Password length as per settings #67
- [x] Bump Plugin Version + Format Code #36 
- [x] Native Account e-mail Match #31 
- [x] Complete basic repo structure #17

**Comment by effone** [comment]
I have started working on release of Isango 1.2.0
Targeting to make it a major Bug / Security Fix + Improvements

I have listed down all the focus for this in a task list. Feel free to alter the task list as you please.

**Comment by Eldenroot** [comment]
Great! Nice progress so far! If anything let me know .)

**Comment by effone** [comment]
With the vast changes in code, and introducing additional template I really feel we should bump the plugin version to 2.0.0
Though I have handled settings but simply reactivating the plugin will not help inserting new templates.

**Comment by Eldenroot** [comment]
Sure thing.

**Comment by Eldenroot** [comment]
@effone - please, could you finish the latest missing features and release a new build?
